Resources:
  ALayeredFunctionRoleE0BF22A9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: ALayeredFunctionRole
    Metadata:
      aws:cdk:path: LayerCdkStack/ALayeredFunctionRole/Resource
  ALayeredFunctionRoleDefaultPolicy592A167D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Effect: Allow
            Resource: arn:aws:sqs:*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ALayeredFunctionRoleDefaultPolicy592A167D
      Roles:
        - Ref: ALayeredFunctionRoleE0BF22A9
    Metadata:
      aws:cdk:path: LayerCdkStack/ALayeredFunctionRole/DefaultPolicy/Resource
  ALayeredFunctionNodeModuleLayer5021658A:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParametersc5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9dS3Bucket2162FD2B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9dS3VersionKey0673FBFE
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9dS3VersionKey0673FBFE
      CompatibleRuntimes:
        - nodejs12.x
      Description: A Layered Function Node_Module Layer
      LayerName: ALayeredFunctionNodeModuleLayer
    Metadata:
      aws:cdk:path: LayerCdkStack/ALayeredFunctionNodeModuleLayer/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/layer-cdk/layer/a-layered-function-node-module-layer
      aws:asset:property: Content
  ALayeredFunctionF98340AD:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2S3Bucket870EE9A9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2S3VersionKeyF306612D
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2S3VersionKeyF306612D
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - ALayeredFunctionRoleE0BF22A9
          - Arn
      Runtime: nodejs12.x
      FunctionName: ALayeredFunction
      Layers:
        - Ref: ALayeredFunctionNodeModuleLayer5021658A
    DependsOn:
      - ALayeredFunctionRoleDefaultPolicy592A167D
      - ALayeredFunctionRoleE0BF22A9
    Metadata:
      aws:cdk:path: LayerCdkStack/ALayeredFunction/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/layer-cdk/lambda/a-layered-function
      aws:asset:property: Code
Parameters:
  AssetParametersc5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9dS3Bucket2162FD2B:
    Type: String
    Description: S3 bucket for asset "c5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9d"
  AssetParametersc5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9dS3VersionKey0673FBFE:
    Type: String
    Description: S3 key for asset version "c5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9d"
  AssetParametersc5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9dArtifactHash5E733E8C:
    Type: String
    Description: Artifact hash for asset "c5b9d02e8c99e39da8b1485c069528e80c35626cbee37984e400c23b2d599d9d"
  AssetParameters19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2S3Bucket870EE9A9:
    Type: String
    Description: S3 bucket for asset "19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2"
  AssetParameters19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2S3VersionKeyF306612D:
    Type: String
    Description: S3 key for asset version "19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2"
  AssetParameters19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2ArtifactHash19FA0AD5:
    Type: String
    Description: Artifact hash for asset "19b8b6ea4fbf8dce0c7d05587b08b88fc3df06a25bdfa731e4035350bafe3da2"

