Description: S3-LAMBDA-TEMP-CDK-STACK
Resources:
  S3LAMBDATEMPBUCKETD1C47A94:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-lambda-temp-bucket.huge.head.li
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: S3-LAMBDA-TEMP-CDK-STACK/S3_LAMBDA_TEMP_BUCKET/Resource
  S3LAMBDATEMPLAMBDAROLE74022B3F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: S3_LAMBDA_TEMP_LAMBDA_ROLE
      RoleName: S3_LAMBDA_TEMP_LAMBDA_ROLE
    Metadata:
      aws:cdk:path: S3-LAMBDA-TEMP-CDK-STACK/S3_LAMBDA_TEMP_LAMBDA_ROLE/Resource
  S3LAMBDATEMPLAMBDAROLEDefaultPolicyB1C64AAE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: S3LAMBDATEMPLAMBDAROLEDefaultPolicyB1C64AAE
      Roles:
        - Ref: S3LAMBDATEMPLAMBDAROLE74022B3F
    Metadata:
      aws:cdk:path: S3-LAMBDA-TEMP-CDK-STACK/S3_LAMBDA_TEMP_LAMBDA_ROLE/DefaultPolicy/Resource
  S3LAMBDATEMPLAMBDA853AB85C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3eS3BucketE51211B1
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3eS3VersionKeyB0345410
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3eS3VersionKeyB0345410
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - S3LAMBDATEMPLAMBDAROLE74022B3F
          - Arn
      Runtime: nodejs12.x
      Description: S3_LAMBDA_TEMP_LAMBDA
      FunctionName: S3_LAMBDA_TEMP_LAMBDA
      MemorySize: 256
      Timeout: 15
    DependsOn:
      - S3LAMBDATEMPLAMBDAROLEDefaultPolicyB1C64AAE
      - S3LAMBDATEMPLAMBDAROLE74022B3F
    Metadata:
      aws:cdk:path: S3-LAMBDA-TEMP-CDK-STACK/S3_LAMBDA_TEMP_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/s3-lambda-temp-cdk/lambdas/s3-lambda-temp-lambda
      aws:asset:property: Code
Parameters:
  AssetParameters252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3eS3BucketE51211B1:
    Type: String
    Description: S3 bucket for asset "252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3e"
  AssetParameters252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3eS3VersionKeyB0345410:
    Type: String
    Description: S3 key for asset version "252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3e"
  AssetParameters252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3eArtifactHash62B9E5B0:
    Type: String
    Description: Artifact hash for asset "252fad72c14ef75f1c1c694e2b3147289d56534dc150b257770dd236c3a71b3e"

