module.exports = {
  SQS_NAME: 'SLACK_TECH_SUPPORT_QUEUE',
  SLACK_BOT_LAMBDA_ROLE_NAME: 'SLACK_BOT_LAMBDA_ROLE',
  SLACK_BOT_DEPENDENCY_LAYER_NAME: 'SLACK_BOT_DEPENDENCY_LAYER',
  SLACK_BOT_SQS_PUBLISHER_NAME: 'SLACK_BOT_SQS_PUBLISHER',
  SLACK_BOT_SQS_PUBLISHER_API_NAME: 'SLACK_BOT_SQS_PUBLISHER_API',
  SLACK_BOT_SQS_CONSUMER_NAME: 'SLACK_BOT_SQS_CONSUMER',
  SLACK_BOT_DIRECT_JIRA_CREATOR_NAME: 'SLACK_BOT_DIRECT_JIRA_CREATOR'
};