Resources:
  APIASimpleExampleSTACKLAMBDAROLEB2001963:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: LAMBDA-ROLE
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-LAMBDA-ROLE/Resource
  APIASimpleExampleSTACKLAMBDAROLEDefaultPolicyE05F6AD8:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: APIASimpleExampleSTACKLAMBDAROLEDefaultPolicyE05F6AD8
      Roles:
        - Ref: APIASimpleExampleSTACKLAMBDAROLEB2001963
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-LAMBDA-ROLE/DefaultPolicy/Resource
  APIASimpleExampleSTACKEXAMPLELAMBDAC617CDA5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 9c0f2d78e5cb94fe3f474d1f49ed217cde266dc8787f6aa3ca48ee16e7a521ab.zip
      Role:
        Fn::GetAtt:
          - APIASimpleExampleSTACKLAMBDAROLEB2001963
          - Arn
      FunctionName: EXAMPLE-LAMBDA
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 15
    DependsOn:
      - APIASimpleExampleSTACKLAMBDAROLEDefaultPolicyE05F6AD8
      - APIASimpleExampleSTACKLAMBDAROLEB2001963
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/api-gwy/api-a-simple-example/lambdas/AFunction
      aws:asset:is-bundled: false
      aws:asset:property: Code
  APIASimpleExampleSTACKEXAMPLELAMBDAApiAccessPermission20E2C882:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - APIASimpleExampleSTACKEXAMPLELAMBDAC617CDA5
          - Arn
      Principal: apigateway.amazonaws.com
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-LAMBDA/ApiAccessPermission
  APIASimpleExampleSTACKEXAMPLEAPIGW774D8041:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: EXAMPLE-API-GW
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: EXAMPLE-API-GW
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Resource
  APIASimpleExampleSTACKEXAMPLEAPIGWCloudWatchRoleBE1A1F52:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/CloudWatchRole/Resource
  APIASimpleExampleSTACKEXAMPLEAPIGWAccount8EE6D0DF:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - APIASimpleExampleSTACKEXAMPLEAPIGWCloudWatchRoleBE1A1F52
          - Arn
    DependsOn:
      - APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Account
  APIASimpleExampleSTACKEXAMPLEAPIGWDeployment6F3E0B35d49fe3f4f7c76628a3675bbe84db61a0:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
      Description: Automatically created by the RestApi construct
    DependsOn:
      - APIASimpleExampleSTACKEXAMPLEAPIGWexampleGETC5ABCDBF
      - APIASimpleExampleSTACKEXAMPLEAPIGWexample466286C4
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Deployment/Resource
  APIASimpleExampleSTACKEXAMPLEAPIGWDeploymentStageprodCAA932DD:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
      DeploymentId:
        Ref: APIASimpleExampleSTACKEXAMPLEAPIGWDeployment6F3E0B35d49fe3f4f7c76628a3675bbe84db61a0
      StageName: prod
    DependsOn:
      - APIASimpleExampleSTACKEXAMPLEAPIGWAccount8EE6D0DF
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/DeploymentStage.prod/Resource
  APIASimpleExampleSTACKEXAMPLEAPIGWexample466286C4:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
          - RootResourceId
      PathPart: example
      RestApiId:
        Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Default/example/Resource
  APIASimpleExampleSTACKEXAMPLEAPIGWexampleGETApiPermissionAPIASimpleExampleSTACKAPIASimpleExampleSTACKEXAMPLEAPIGW6BB9A956GETexample59DB91A5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - APIASimpleExampleSTACKEXAMPLELAMBDAC617CDA5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
            - /
            - Ref: APIASimpleExampleSTACKEXAMPLEAPIGWDeploymentStageprodCAA932DD
            - /GET/example
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Default/example/GET/ApiPermission.APIASimpleExampleSTACKAPIASimpleExampleSTACKEXAMPLEAPIGW6BB9A956.GET..example
  APIASimpleExampleSTACKEXAMPLEAPIGWexampleGETApiPermissionTestAPIASimpleExampleSTACKAPIASimpleExampleSTACKEXAMPLEAPIGW6BB9A956GETexample549678F1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - APIASimpleExampleSTACKEXAMPLELAMBDAC617CDA5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
            - /test-invoke-stage/GET/example
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Default/example/GET/ApiPermission.Test.APIASimpleExampleSTACKAPIASimpleExampleSTACKEXAMPLEAPIGW6BB9A956.GET..example
  APIASimpleExampleSTACKEXAMPLEAPIGWexampleGETC5ABCDBF:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: APIASimpleExampleSTACKEXAMPLEAPIGWexample466286C4
      RestApiId:
        Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - APIASimpleExampleSTACKEXAMPLELAMBDAC617CDA5
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: API-ASimple-Example-STACK/API-ASimple-Example-STACK-EXAMPLE-API-GW/Default/example/GET/Resource
Outputs:
  APIASimpleExampleSTACKEXAMPLEAPIGWEndpointD76EFE64:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: APIASimpleExampleSTACKEXAMPLEAPIGW774D8041
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: APIASimpleExampleSTACKEXAMPLEAPIGWDeploymentStageprodCAA932DD
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

