Description: STEP-FUNCTION-PARALLEL-CDK-STACK
Resources:
  SFNPARALLELTESTBUCKETE387CE66:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sfn-parallel-test-bucket.huge.head.li
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_BUCKET/Resource
  SFNPARALLELTESTROLE322ED782:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: SFN_PARALLEL_TEST_ROLE
      RoleName: SFN_PARALLEL_TEST_ROLE
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_ROLE/Resource
  SFNPARALLELTESTROLEDefaultPolicy61DAA1CE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: SFNPARALLELTESTROLEDefaultPolicy61DAA1CE
      Roles:
        - Ref: SFNPARALLELTESTROLE322ED782
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_ROLE/DefaultPolicy/Resource
  SFNPARALLELTESTS3WRITTERLAMBDA4D810B0C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782fS3Bucket856DA546
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782fS3VersionKeyA6193D6B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782fS3VersionKeyA6193D6B
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - SFNPARALLELTESTROLE322ED782
          - Arn
      Runtime: nodejs12.x
      Description: SFN_PARALLEL_TEST_S3_WRITTER_LAMBDA
      FunctionName: SFN_PARALLEL_TEST_S3_WRITTER_LAMBDA
      MemorySize: 256
      Timeout: 15
    DependsOn:
      - SFNPARALLELTESTROLEDefaultPolicy61DAA1CE
      - SFNPARALLELTESTROLE322ED782
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_S3_WRITTER_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/step-function-parallel-cdk/lambdas/sfn-parallel-test-s3-writter-lambda
      aws:asset:property: Code
  SFNPARALLELTESTPASSTHROUGHLAMBDAFFBDA6B3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersf91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145S3Bucket361FFD48
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersf91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145S3VersionKeyEE07A6E9
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersf91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145S3VersionKeyEE07A6E9
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - SFNPARALLELTESTROLE322ED782
          - Arn
      Runtime: nodejs12.x
      Description: SFN_PARALLEL_TEST_PASSTHROUGH_LAMBDA
      FunctionName: SFN_PARALLEL_TEST_PASSTHROUGH_LAMBDA
      MemorySize: 256
      Timeout: 60
    DependsOn:
      - SFNPARALLELTESTROLEDefaultPolicy61DAA1CE
      - SFNPARALLELTESTROLE322ED782
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_PASSTHROUGH_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/step-function-parallel-cdk/lambdas/sfn-parallel-test-passthrough-lambda
      aws:asset:property: Code
  SFNPARALLELTESTSTATEMACHINERoleC78A3911:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_STATE_MACHINE/Role/Resource
  SFNPARALLELTESTSTATEMACHINERoleDefaultPolicy35DE8582:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - SFNPARALLELTESTPASSTHROUGHLAMBDAFFBDA6B3
                - Arn
        Version: "2012-10-17"
      PolicyName: SFNPARALLELTESTSTATEMACHINERoleDefaultPolicy35DE8582
      Roles:
        - Ref: SFNPARALLELTESTSTATEMACHINERoleC78A3911
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_STATE_MACHINE/Role/DefaultPolicy/Resource
  SFNPARALLELTESTSTATEMACHINE8A6C310B:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - SFNPARALLELTESTSTATEMACHINERoleC78A3911
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"SFN_PARALLEL_TEST_STEP_1","States":{"SFN_PARALLEL_TEST_STEP_1":{"End":true,"Type":"Task","OutputPath":"$.Payload","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"
            - Fn::GetAtt:
                - SFNPARALLELTESTPASSTHROUGHLAMBDAFFBDA6B3
                - Arn
            - '","Payload":{"timeout":20}}}},"TimeoutSeconds":300}'
      StateMachineName: SFN_PARALLEL_TEST_STATE_MACHINE
    DependsOn:
      - SFNPARALLELTESTSTATEMACHINERoleDefaultPolicy35DE8582
      - SFNPARALLELTESTSTATEMACHINERoleC78A3911
    Metadata:
      aws:cdk:path: STEP-FUNCTION-PARALLEL-CDK-STACK/SFN_PARALLEL_TEST_STATE_MACHINE/Resource
Parameters:
  AssetParameters59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782fS3Bucket856DA546:
    Type: String
    Description: S3 bucket for asset "59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782f"
  AssetParameters59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782fS3VersionKeyA6193D6B:
    Type: String
    Description: S3 key for asset version "59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782f"
  AssetParameters59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782fArtifactHash73785BE7:
    Type: String
    Description: Artifact hash for asset "59d1e746da6c84fa64236c4655f51249f8e930430eb43d2dc50bfa2fd3bd782f"
  AssetParametersf91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145S3Bucket361FFD48:
    Type: String
    Description: S3 bucket for asset "f91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145"
  AssetParametersf91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145S3VersionKeyEE07A6E9:
    Type: String
    Description: S3 key for asset version "f91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145"
  AssetParametersf91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145ArtifactHashC23440FA:
    Type: String
    Description: Artifact hash for asset "f91c58574a3ccd88a373fa99fc5e8793076ec4d32831488c4191621f38708145"

