#!/bin/bash

cd lambda/LambdaDotnetLayer

publish_directory="publish"
if [ -d ${publish_directory} ]; then
    rm -rf ${publish_directory}
fi

store_directory="${publish_directory}/store"

donet clean

dotnet store \
  --manifest LambdaDotnetLayer.csproj \
  --output ${store_directory} --skip-optimization \
  --runtime linux-x64 \
  --framework netcoreapp3.1 --framework-version 3.1.0

# package="../../../package.zip"
# cd "${store_directory}/x64/netcoreapp3.1/"

package="package.zip"
cd ${publish_directory}

zip -r ${package} .