Description: API-CDK-STACK
Resources:
  APICDKSTACKMyRole834BC275:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: API-CDK-STACKMyRole
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKMyRole/Resource
  APICDKSTACKMyRoleDefaultPolicy6490C780:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: APICDKSTACKMyRoleDefaultPolicy6490C780
      Roles:
        - Ref: APICDKSTACKMyRole834BC275
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKMyRole/DefaultPolicy/Resource
  APICDKSTACKAFunctionEB984721:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3acS3BucketFFA2469D
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3acS3VersionKey100A561C
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3acS3VersionKey100A561C
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - APICDKSTACKMyRole834BC275
          - Arn
      Runtime: nodejs12.x
      FunctionName: API-CDK-STACKAFunction
      Timeout: 120
    DependsOn:
      - APICDKSTACKMyRoleDefaultPolicy6490C780
      - APICDKSTACKMyRole834BC275
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAFunction/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/api-cdk/lambda/AFunction
      aws:asset:property: Code
  APICDKSTACKAPIGWAA193FB7:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API-CDK-STACKAPIGW
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: API-CDK-STACKAPIGW
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Resource
  APICDKSTACKAPIGWCloudWatchRole1B5323E8:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/CloudWatchRole/Resource
  APICDKSTACKAPIGWAccountE4AA8DA7:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - APICDKSTACKAPIGWCloudWatchRole1B5323E8
          - Arn
    DependsOn:
      - APICDKSTACKAPIGWAA193FB7
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Account
  APICDKSTACKAPIGWDeployment2FE7C019880a1d0401f29584a19b02031e52b25e:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
      Description: Automatically created by the RestApi construct
    DependsOn:
      - APICDKSTACKAPIGWattachkeyOPTIONSBB1C3EDE
      - APICDKSTACKAPIGWattachkeyPOST3814CF79
      - APICDKSTACKAPIGWattachkeyA4C8506C
      - APICDKSTACKAPIGWattachOPTIONS0406BF46
      - APICDKSTACKAPIGWattach0E11F2B6
      - APICDKSTACKAPIGWOPTIONS74E74280
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Deployment/Resource
  APICDKSTACKAPIGWDeploymentStageprod2B95DB1B:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
      DeploymentId:
        Ref: APICDKSTACKAPIGWDeployment2FE7C019880a1d0401f29584a19b02031e52b25e
      StageName: prod
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/DeploymentStage.prod/Resource
  APICDKSTACKAPIGWOPTIONS74E74280:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Fn::GetAtt:
          - APICDKSTACKAPIGWAA193FB7
          - RootResourceId
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/OPTIONS/Resource
  APICDKSTACKAPIGWattach0E11F2B6:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - APICDKSTACKAPIGWAA193FB7
          - RootResourceId
      PathPart: attach
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/Resource
  APICDKSTACKAPIGWattachOPTIONS0406BF46:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Ref: APICDKSTACKAPIGWattach0E11F2B6
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/OPTIONS/Resource
  APICDKSTACKAPIGWattachkeyA4C8506C:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Ref: APICDKSTACKAPIGWattach0E11F2B6
      PathPart: "{key}"
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/{key}/Resource
  APICDKSTACKAPIGWattachkeyOPTIONSBB1C3EDE:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Ref: APICDKSTACKAPIGWattachkeyA4C8506C
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/{key}/OPTIONS/Resource
  APICDKSTACKAPIGWattachkeyPOSTApiPermissionAPICDKSTACKAPICDKSTACKAPIGW52E3ED44POSTattachkey56C391CE:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - APICDKSTACKAFunctionEB984721
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: APICDKSTACKAPIGWAA193FB7
            - /
            - Ref: APICDKSTACKAPIGWDeploymentStageprod2B95DB1B
            - /POST/attach/*
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/{key}/POST/ApiPermission.APICDKSTACKAPICDKSTACKAPIGW52E3ED44.POST..attach.{key}
  APICDKSTACKAPIGWattachkeyPOSTApiPermissionTestAPICDKSTACKAPICDKSTACKAPIGW52E3ED44POSTattachkeyE8267E58:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - APICDKSTACKAFunctionEB984721
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: APICDKSTACKAPIGWAA193FB7
            - /test-invoke-stage/POST/attach/*
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/{key}/POST/ApiPermission.Test.APICDKSTACKAPICDKSTACKAPIGW52E3ED44.POST..attach.{key}
  APICDKSTACKAPIGWattachkeyPOST3814CF79:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: APICDKSTACKAPIGWattachkeyA4C8506C
      RestApiId:
        Ref: APICDKSTACKAPIGWAA193FB7
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - APICDKSTACKAFunctionEB984721
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: API-CDK-STACK/API-CDK-STACKAPIGW/Default/attach/{key}/POST/Resource
Parameters:
  AssetParameters9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3acS3BucketFFA2469D:
    Type: String
    Description: S3 bucket for asset "9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3ac"
  AssetParameters9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3acS3VersionKey100A561C:
    Type: String
    Description: S3 key for asset version "9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3ac"
  AssetParameters9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3acArtifactHash49764404:
    Type: String
    Description: Artifact hash for asset "9e351bed2b1cc95f9e93ac3e9df4dac7f27446b9a7480743147273ddba71e3ac"
Outputs:
  APICDKSTACKAPIGWEndpointF8CFD52F:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: APICDKSTACKAPIGWAA193FB7
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: APICDKSTACKAPIGWDeploymentStageprod2B95DB1B
          - /

