#!/bin/bash

cd lambda/LambdaDotnetLayerExample

publish_directory="publish"
if [ -d ${publish_directory} ]; then
    rm -rf ${publish_directory}
fi

package_file="${publish_directory}/package.zip"

layer_zip="/home/song/Sandbox/aws-cdk-examples/dotnet-lambda-layer-cdk/lambda/LambdaDotnetLayer/publish/package.zip"

dotnet clean
dotnet lambda package --function-layers ${layer_zip} -o ${package_file}