version: "3.7"
services:
  postgres:
    image: postgres:14
    container_name: postgres-15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres