Resources:
  MyRoleF48FFE04:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: MyRole
    Metadata:
      aws:cdk:path: SqsCdkStack/MyRole/Resource
  MyRoleDefaultPolicyA36BE1DD:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Effect: Allow
            Resource: arn:aws:sqs:*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - ATestSQSQueueA57F8D90
                - Arn
        Version: "2012-10-17"
      PolicyName: MyRoleDefaultPolicyA36BE1DD
      Roles:
        - Ref: MyRoleF48FFE04
    Metadata:
      aws:cdk:path: SqsCdkStack/MyRole/DefaultPolicy/Resource
  ATestSQSQueueA57F8D90:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ATestSQSQueue
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 180
    Metadata:
      aws:cdk:path: SqsCdkStack/ATestSQSQueue/Resource
  ATestSQSQueuePolicyDC5EA50C:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::GetAtt:
                - ATestSQSQueueA57F8D90
                - Arn
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::GetAtt:
                - ATestSQSQueueA57F8D90
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: ATestSQSQueueA57F8D90
    Metadata:
      aws:cdk:path: SqsCdkStack/ATestSQSQueue/Policy/Resource
  ATestSQSConsumerFunction752F0C36:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89S3Bucket2193620B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89S3VersionKey3D43EBD2
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89S3VersionKey3D43EBD2
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - MyRoleF48FFE04
          - Arn
      Runtime: nodejs12.x
      FunctionName: ATestSQSConsumerFunction
    DependsOn:
      - MyRoleDefaultPolicyA36BE1DD
      - MyRoleF48FFE04
    Metadata:
      aws:cdk:path: SqsCdkStack/ATestSQSConsumerFunction/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/sqs-cdk/lambda/sqs-consumer
      aws:asset:property: Code
  ATestSQSConsumerFunctionSqsEventSourceSqsCdkStackATestSQSQueueD595DB087EAB2A2D:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - ATestSQSQueueA57F8D90
          - Arn
      FunctionName:
        Ref: ATestSQSConsumerFunction752F0C36
      BatchSize: 1
    Metadata:
      aws:cdk:path: SqsCdkStack/ATestSQSConsumerFunction/SqsEventSource:SqsCdkStackATestSQSQueueD595DB08/Resource
  ATestSQSPublisherFunctionDB129046:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88S3Bucket870481E6
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88S3VersionKeyAD36C4E7
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88S3VersionKeyAD36C4E7
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - MyRoleF48FFE04
          - Arn
      Runtime: nodejs12.x
      FunctionName: ATestSQSPublisherFunction
    DependsOn:
      - MyRoleDefaultPolicyA36BE1DD
      - MyRoleF48FFE04
    Metadata:
      aws:cdk:path: SqsCdkStack/ATestSQSPublisherFunction/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/sqs-cdk/lambda/sqs-publisher
      aws:asset:property: Code
Parameters:
  AssetParameters324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89S3Bucket2193620B:
    Type: String
    Description: S3 bucket for asset "324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89"
  AssetParameters324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89S3VersionKey3D43EBD2:
    Type: String
    Description: S3 key for asset version "324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89"
  AssetParameters324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89ArtifactHash2DC8FFE8:
    Type: String
    Description: Artifact hash for asset "324ee804d69eb74a7b1f97ea7d63230ac333892ba57b8a83cf6ba391f66fff89"
  AssetParameters1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88S3Bucket870481E6:
    Type: String
    Description: S3 bucket for asset "1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88"
  AssetParameters1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88S3VersionKeyAD36C4E7:
    Type: String
    Description: S3 key for asset version "1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88"
  AssetParameters1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88ArtifactHashED8E7343:
    Type: String
    Description: Artifact hash for asset "1acf027afdd3f89703ef385a428f190ed51b100d23486c460d162aa73e892f88"

