module.exports = {
  SQS_NAME: 'SNOWFLAKE_S3_PIPE_AUTOMATION_QUEUE',
  SNOWFLAKE_S3_PIPE_DEPENDENCY_LAYER_NAME: 'SNOWFLAKE_S3_PIPE_DEPENDENCY_LAYER',
  SNOWFLAKE_S3_PIPE_STARTER_NAME: 'SNOWFLAKE_S3_PIPE_STARTER'
};
