Description: LAUNCH-EC2-CDK-STACK
Resources:
  LAUNCHEC2CDKSTACKEC2LAUNCHROLE7F812DBF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE
      RoleName: LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE/Resource
  LAUNCHEC2CDKSTACKEC2LAUNCHROLEDefaultPolicy51D054DD:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action: ec2:RunInstances
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: LAUNCHEC2CDKSTACKEC2LAUNCHROLEDefaultPolicy51D054DD
      Roles:
        - Ref: LAUNCHEC2CDKSTACKEC2LAUNCHROLE7F812DBF
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE/DefaultPolicy/Resource
  LAUNCHEC2CDKSTACKLAUNCHEC2LAMBDAA04184E1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersbd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02S3Bucket75492C46
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02S3VersionKey538CB8DC
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02S3VersionKey538CB8DC
      Handler: index.lambdaHandler
      Role:
        Fn::GetAtt:
          - LAUNCHEC2CDKSTACKEC2LAUNCHROLE7F812DBF
          - Arn
      Runtime: nodejs12.x
      Description: LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA
      FunctionName: LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA
      MemorySize: 128
      Timeout: 5
    DependsOn:
      - LAUNCHEC2CDKSTACKEC2LAUNCHROLEDefaultPolicy51D054DD
      - LAUNCHEC2CDKSTACKEC2LAUNCHROLE7F812DBF
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/launch-ec2-cdk/lambdas/launch-ec2-lambda
      aws:asset:property: Code
Parameters:
  AssetParametersbd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02S3Bucket75492C46:
    Type: String
    Description: S3 bucket for asset "bd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02"
  AssetParametersbd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02S3VersionKey538CB8DC:
    Type: String
    Description: S3 key for asset version "bd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02"
  AssetParametersbd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02ArtifactHash8A269564:
    Type: String
    Description: Artifact hash for asset "bd50218b136b0f508e69d10d14991181e41c5047ccf0c8ea134142ff03a1bf02"

