Description: LAUNCH-EC2-CDK-STACK
Resources:
  LAUNCHEC2CDKSTACKEC2LAUNCHROLE7F812DBF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE
      RoleName: LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE/Resource
  LAUNCHEC2CDKSTACKEC2LAUNCHROLEDefaultPolicy51D054DD:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ec2:RunInstances
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: LAUNCHEC2CDKSTACKEC2LAUNCHROLEDefaultPolicy51D054DD
      Roles:
        - Ref: LAUNCHEC2CDKSTACKEC2LAUNCHROLE7F812DBF
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-EC2-LAUNCH-ROLE/DefaultPolicy/Resource
  LAUNCHEC2CDKSTACKLAUNCHEC2LAMBDAServiceRole960190D7:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA/ServiceRole/Resource
  LAUNCHEC2CDKSTACKLAUNCHEC2LAMBDAA04184E1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310S3BucketD0C2247D
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310S3VersionKeyA669D681
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310S3VersionKeyA669D681
      Handler: index.lambdaHandler
      Role:
        Fn::GetAtt:
          - LAUNCHEC2CDKSTACKLAUNCHEC2LAMBDAServiceRole960190D7
          - Arn
      Runtime: nodejs12.x
      Description: LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA
      FunctionName: LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA
      MemorySize: 128
      Timeout: 5
    DependsOn:
      - LAUNCHEC2CDKSTACKLAUNCHEC2LAMBDAServiceRole960190D7
    Metadata:
      aws:cdk:path: LAUNCH-EC2-CDK-STACK/LAUNCH-EC2-CDK-STACK-LAUNCH_EC2_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/launch-ec2-cdk/lambdas/launch-ec2-lambda
      aws:asset:property: Code
Parameters:
  AssetParametersab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310S3BucketD0C2247D:
    Type: String
    Description: S3 bucket for asset "ab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310"
  AssetParametersab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310S3VersionKeyA669D681:
    Type: String
    Description: S3 key for asset version "ab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310"
  AssetParametersab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310ArtifactHash9BFFC94D:
    Type: String
    Description: Artifact hash for asset "ab8bc78c2f051df8459f2720af708dd2d5f925f8d625b1bc7c6b022debb5e310"

