Resources:
  ApiSnowflakeExternalFunctionCdkStacklambdarole2E25FB11:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: ApiSnowflakeExternalFunctionCdkStack-lambda-role
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-lambda-role/Resource
  ApiSnowflakeExternalFunctionCdkStacklambdaroleDefaultPolicy9F9B0665:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ApiSnowflakeExternalFunctionCdkStacklambdaroleDefaultPolicy9F9B0665
      Roles:
        - Ref: ApiSnowflakeExternalFunctionCdkStacklambdarole2E25FB11
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-lambda-role/DefaultPolicy/Resource
  ApiSnowflakeExternalFunctionCdkStackapihandler41EC88AA:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersb6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450bS3Bucket6565017A
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersb6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450bS3VersionKey1EAE5F37
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersb6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450bS3VersionKey1EAE5F37
      Role:
        Fn::GetAtt:
          - ApiSnowflakeExternalFunctionCdkStacklambdarole2E25FB11
          - Arn
      FunctionName: ApiSnowflakeExternalFunctionCdkStack-api-handler
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 15
    DependsOn:
      - ApiSnowflakeExternalFunctionCdkStacklambdaroleDefaultPolicy9F9B0665
      - ApiSnowflakeExternalFunctionCdkStacklambdarole2E25FB11
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-api-handler/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/api-snowflake-external-function-cdk/lambda/api-handler
      aws:asset:property: Code
  ApiSnowflakeExternalFunctionCdkStackapihandlerApiAccessPermission9065F686:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ApiSnowflakeExternalFunctionCdkStackapihandler41EC88AA
          - Arn
      Principal: apigateway.amazonaws.com
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-api-handler/ApiAccessPermission
  ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: ApiSnowflakeExternalFunctionCdkStack-API
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: ApiSnowflakeExternalFunctionCdkStack-API
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/Resource
  ApiSnowflakeExternalFunctionCdkStackAPICloudWatchRole96C22CA9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/CloudWatchRole/Resource
  ApiSnowflakeExternalFunctionCdkStackAPIAccountDD60CB7A:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - ApiSnowflakeExternalFunctionCdkStackAPICloudWatchRole96C22CA9
          - Arn
    DependsOn:
      - ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/Account
  ApiSnowflakeExternalFunctionCdkStackAPIDeploymentC60B54EC4e323badbcab4c499c0b10b516011191:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
      Description: Automatically created by the RestApi construct
    DependsOn:
      - ApiSnowflakeExternalFunctionCdkStackAPIPOST2FBB30FC
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/Deployment/Resource
  ApiSnowflakeExternalFunctionCdkStackAPIDeploymentStageprod23D0B2FE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
      DeploymentId:
        Ref: ApiSnowflakeExternalFunctionCdkStackAPIDeploymentC60B54EC4e323badbcab4c499c0b10b516011191
      StageName: prod
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/DeploymentStage.prod/Resource
  ApiSnowflakeExternalFunctionCdkStackAPIPOSTApiPermissionApiSnowflakeExternalFunctionCdkStackApiSnowflakeExternalFunctionCdkStackAPI2653AE7CPOST2DEEA88A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ApiSnowflakeExternalFunctionCdkStackapihandler41EC88AA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
            - /
            - Ref: ApiSnowflakeExternalFunctionCdkStackAPIDeploymentStageprod23D0B2FE
            - /POST/
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/Default/POST/ApiPermission.ApiSnowflakeExternalFunctionCdkStackApiSnowflakeExternalFunctionCdkStackAPI2653AE7C.POST..
  ApiSnowflakeExternalFunctionCdkStackAPIPOSTApiPermissionTestApiSnowflakeExternalFunctionCdkStackApiSnowflakeExternalFunctionCdkStackAPI2653AE7CPOSTDBECBD37:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ApiSnowflakeExternalFunctionCdkStackapihandler41EC88AA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
            - /test-invoke-stage/POST/
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/Default/POST/ApiPermission.Test.ApiSnowflakeExternalFunctionCdkStackApiSnowflakeExternalFunctionCdkStackAPI2653AE7C.POST..
  ApiSnowflakeExternalFunctionCdkStackAPIPOST2FBB30FC:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Fn::GetAtt:
          - ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
          - RootResourceId
      RestApiId:
        Ref: ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - ApiSnowflakeExternalFunctionCdkStackapihandler41EC88AA
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: ApiSnowflakeExternalFunctionCdkStack/ApiSnowflakeExternalFunctionCdkStack-API/Default/POST/Resource
Parameters:
  AssetParametersb6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450bS3Bucket6565017A:
    Type: String
    Description: S3 bucket for asset "b6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450b"
  AssetParametersb6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450bS3VersionKey1EAE5F37:
    Type: String
    Description: S3 key for asset version "b6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450b"
  AssetParametersb6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450bArtifactHashB46E3353:
    Type: String
    Description: Artifact hash for asset "b6019b302f1ae6b85b615bb72dc2db8d8a1b8e85fdec38f7a30c8e78d349450b"
Outputs:
  ApiSnowflakeExternalFunctionCdkStackAPIEndpointAD5C72C1:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: ApiSnowflakeExternalFunctionCdkStackAPIE5E914DA
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: ApiSnowflakeExternalFunctionCdkStackAPIDeploymentStageprod23D0B2FE
          - /

