#!/bin/bash

# https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
#!/bin/bash

# https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-cli.html#nuget-consume-cli

# dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
# dotnet codeartifact-creds install
# dotnet codeartifact-creds configure set profile huge-head-li-2021

# aws codeartifact login --tool dotnet --domain testdomain --domain-owner 660079349745 --repository testnugetrepo

# Cross account
# https://docs.aws.amazon.com/codeartifact/latest/ug/domain-policies.html#enabling-cross-acount-access-to-a-domain

cd examples/nuget/ExamplePackage

package_directory="nuget-package-directory"

dotnet clean
status=$(echo $(dotnet pack -o ${package_directory} | grep "Successfully created package"))

echo ${status}

nupkg=$(echo ${status} | grep -o "${package_directory}.*")
nupkg=$(echo ${nupkg::-2})
echo $nupkg

dotnet nuget push $nupkg --skip-duplicate --source testdomain/testnugetrepo