#!/bin/bash

# https://docs.aws.amazon.com/codeartifact/latest/ug/using-npm.html


cd examples/npm/ExamplePackage

# aws codeartifact login --tool npm --domain testdomain --repository testnugetrepo
npm publish