#!/bin/bash

# https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
#!/bin/bash

# https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-cli.html#nuget-consume-cli

# dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
# dotnet codeartifact-creds install
# dotnet codeartifact-creds configure set profile huge-head-li-2021

# aws codeartifact login --tool dotnet --domain testdomain --domain-owner 660079349745 --repository testnugetrepo

# Cross account
# https://docs.aws.amazon.com/codeartifact/latest/ug/domain-policies.html#enabling-cross-acount-access-to-a-domain

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

# export AWS_ACCESS_KEY_ID=access...id
# export AWS_SECRET_ACCESS_KEY=secrte...access...key

# dotnet nuget list source
# dotnet nuget add source "https://testdomain-660079349745.d.codeartifact.us-east-1.amazonaws.com/nuget/testnugetrepo/v3/index.json" -n testdomain/testnugetrepo
# dotnet nuget remove testdomain/testnugetrepo

# Cross account permission, need to provide the following permission to the account to access
# the code-artifact
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Effect": "Allow",
#             "Action": "codeartifact:*",
#             "Resource": "*"
#         },
#         {
#             "Effect": "Allow",
#             "Action": "sts:GetServiceBearerToken",
#             "Resource": "*"
#         }
#     ]
# }

publish_nuget() {
  package_directory="nuget-package-directory"

  dotnet clean
  status=$(echo $(dotnet pack -o ${package_directory} | grep "Successfully created package"))

  echo ${status}

  nupkg=$(echo ${status} | grep -o "${package_directory}.*")
  nupkg=$(echo ${nupkg::-2})
  echo $nupkg

  dotnet nuget push $nupkg --skip-duplicate --source testdomain/testnugetrepo
};

cd examples/nuget/ExamplePackage

publish_nuget
