#!/bin/bash

if [ "$1" == "run" ]
then
  task_raw=$(aws ecs run-task \
    --task-definition FARGATETASKCDKSTACKFARGATETASKCDKSTACKFARGATE5599BAAB \
    --launch-type FARGATE \
    --cluster FARGATE-TASK-CDK-STACK-CLUSTER \
    --network-configuration \
      "awsvpcConfiguration={subnets=[subnet-00418f8693296c8c7],securityGroups=[sg-0e49477fd400db151],assignPublicIp=DISABLED}")

  taskArn=$(echo $task_raw | jq '.tasks[0].taskArn')

  echo -e "Task Started\n$taskArn"
fi