#!/bin/bash

if [ "$1" == "run" ]
then
  task_raw=$(aws ecs run-task \
    --task-definition FARGATETASKCDKSTACKFARGATETASKCDKSTACKFARGATE5599BAAB \
    --launch-type FARGATE \
    --cluster FARGATE-TASK-CDK-STACK-CLUSTER \
    --network-configuration \
      "awsvpcConfiguration={subnets=[subnet-03a918bd8b069a863],securityGroups=[sg-0c678492913ace795],assignPublicIp=DISABLED}")

  taskArn=$(echo $task_raw | jq '.tasks[0].taskArn')

  echo -e "Task Started\n$taskArn"
fi