FROM ubuntu:21.04

RUN apt-get update
RUN apt-get install python3.9 -y
RUN apt-get install python3-pip -y
RUN apt-get autoremove -y
RUN python3.9 -m pip install awslambdaric
RUN python3.9 -m pip install torch==1.9.1+cpu torchvision==0.10.1+cpu torchaudio==0.9.1 \
  -f https://download.pytorch.org/whl/torch_stable.html

COPY requirements.txt .
RUN python3.9 -m pip install -r requirements.txt
