# This is the base image recommended by Amazon
# It seems to have much slower cold start than Ubuntu base image
FROM public.ecr.aws/lambda/python:3.8

RUN pip3 install torch==1.9.1+cpu torchvision==0.10.1+cpu torchaudio==0.9.1 \
  -f https://download.pytorch.org/whl/torch_stable.html

COPY requirements.txt .
RUN pip3 install -r requirements.txt

ADD snakers4_silero-models_master /opt/snakers4_silero-models_master
RUN chmod 755 /opt/snakers4_silero-models_master/model/en_v5.jit
ADD files /opt/files

WORKDIR /var/task/
COPY app.py .
COPY identifier.py .

CMD [ "app.lambdaHandler" ]
