#!/bin/bash


SERVICE_NAME='ThisIsMyCaseSensitiveMicroService'
BRANCH='Development'

hyphen=''
function add_hyphen() { if [[ $n =~ [A-Z] ]] && [[ ${hyphen} != '' ]]; then hyphen=${hyphen}-; fi; }
function append_text { n=${SERVICE_NAME:$i:1}; add_hyphen; hyphen=${hyphen}${n,,}; }
for (( i=0; i<${#SERVICE_NAME}; i++ )); do append_text; done

echo 'This is the result of the conversion --------------------------------'
echo ${BRANCH,,}.${hyphen}
echo 'Done'
