#!/bin/bash


SERVICE_NAME='ThisIsMyCaseSensitiveMicroService'
BRANCH='Development'

hyphen='';
for (( i=0; i<${#SERVICE_NAME}; i++ )); do n=${SERVICE_NAME:$i:1}; if [[ $n =~ [A-Z] ]] && [[ ${hyphen} != '' ]]; then hyphen=${hyphen}-; fi; hyphen=${hyphen}${n,,}; done

echo 'This is the result of the conversion --------------------------------'
echo ${BRANCH,,}.${hyphen}
echo 'Done'
