#!/bin/bash

export AWS_DEFAULT_REGION

function destroy {
    REGION=$1
    AWS_DEFAULT_REGION=${REGION}

    echo "Destroying the stack in the region ${REGION}"
    cdk destroy -f
} 

destroy "us-east-1"
destroy "us-east-2"
