#!/bin/bash

cd lambdas/PDF/Word2pdf

DIR=publish
TAG=word2pdf-lambda
if [ -d "$DIR" ]; then
    printf '%s\n' "Removing ($DIR)"
    rm -rf "$DIR"
fi

dotnet publish -c Release -o $DIR

docker build -t word2pdf-lambda:$TAG .
docker system prune -f
