Resources:
  DOCKERLambdaCDKSTACKLAMBDAROLEF240FFB0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: DOCKER-Lambda-CDK-STACK-LAMBDA_ROLE
      RoleName: DOCKER-Lambda-CDK-STACK-LAMBDA_ROLE
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-LAMBDA_ROLE/Resource
  DOCKERLambdaCDKSTACKLAMBDAROLEDefaultPolicy5ADAAAA8:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: DOCKERLambdaCDKSTACKLAMBDAROLEDefaultPolicy5ADAAAA8
      Roles:
        - Ref: DOCKERLambdaCDKSTACKLAMBDAROLEF240FFB0
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-LAMBDA_ROLE/DefaultPolicy/Resource
  DOCKERLambdaCDKSTACKIN240653F3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterse7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946aS3Bucket122BF8BC
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946aS3VersionKey750BDFB9
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946aS3VersionKey750BDFB9
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKLAMBDAROLEF240FFB0
          - Arn
      Runtime: python3.8
      Description: DOCKER-Lambda-CDK-STACK-IN
      FunctionName: DOCKER-Lambda-CDK-STACK-IN
      MemorySize: 1536
      Timeout: 30
    DependsOn:
      - DOCKERLambdaCDKSTACKLAMBDAROLEDefaultPolicy5ADAAAA8
      - DOCKERLambdaCDKSTACKLAMBDAROLEF240FFB0
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/docker-lambda-cdk/lambdas/IN
      aws:asset:property: Code
  DOCKERLambdaCDKSTACKPDF4A081439:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          Fn::Join:
            - ""
            - - Ref: AWS::AccountId
              - .dkr.ecr.
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
              - /word2pdf-lambda:word2pdf-lambda
      Role:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKLAMBDAROLEF240FFB0
          - Arn
      Description: DOCKER-Lambda-CDK-STACK-PDF
      FunctionName: DOCKER-Lambda-CDK-STACK-PDF
      MemorySize: 1536
      PackageType: Image
      Timeout: 30
    DependsOn:
      - DOCKERLambdaCDKSTACKLAMBDAROLEDefaultPolicy5ADAAAA8
      - DOCKERLambdaCDKSTACKLAMBDAROLEF240FFB0
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-PDF/Resource
  DOCKERLambdaCDKSTACKINAPI78B7144F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: DOCKER-Lambda-CDK-STACK-IN-API
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: DOCKER-Lambda-CDK-STACK-IN-API
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Resource
  DOCKERLambdaCDKSTACKINAPICloudWatchRole5D62383C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/CloudWatchRole/Resource
  DOCKERLambdaCDKSTACKINAPIAccountD49E5AB6:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKINAPICloudWatchRole5D62383C
          - Arn
    DependsOn:
      - DOCKERLambdaCDKSTACKINAPI78B7144F
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Account
  DOCKERLambdaCDKSTACKINAPIDeployment6B81791E7da3a030a3811de583a32f00c3eae1ff:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - DOCKERLambdaCDKSTACKINAPIOPTIONS73F9318B
      - DOCKERLambdaCDKSTACKINAPIreceiptOPTIONS6555AC6D
      - DOCKERLambdaCDKSTACKINAPIreceiptPOSTC853DEA1
      - DOCKERLambdaCDKSTACKINAPIreceiptFB018B3A
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Deployment/Resource
  DOCKERLambdaCDKSTACKINAPIDeploymentStageprod1BEFA08B:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
      DeploymentId:
        Ref: DOCKERLambdaCDKSTACKINAPIDeployment6B81791E7da3a030a3811de583a32f00c3eae1ff
      StageName: prod
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/DeploymentStage.prod/Resource
  DOCKERLambdaCDKSTACKINAPIOPTIONS73F9318B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKINAPI78B7144F
          - RootResourceId
      RestApiId:
        Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Default/OPTIONS/Resource
  DOCKERLambdaCDKSTACKINAPIreceiptFB018B3A:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKINAPI78B7144F
          - RootResourceId
      PathPart: receipt
      RestApiId:
        Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Default/receipt/Resource
  DOCKERLambdaCDKSTACKINAPIreceiptOPTIONS6555AC6D:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Ref: DOCKERLambdaCDKSTACKINAPIreceiptFB018B3A
      RestApiId:
        Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Default/receipt/OPTIONS/Resource
  DOCKERLambdaCDKSTACKINAPIreceiptPOSTApiPermissionDOCKERLambdaCDKSTACKDOCKERLambdaCDKSTACKINAPIF087084FPOSTreceiptE66F8CFC:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKIN240653F3
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
            - /
            - Ref: DOCKERLambdaCDKSTACKINAPIDeploymentStageprod1BEFA08B
            - /POST/receipt
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Default/receipt/POST/ApiPermission.DOCKERLambdaCDKSTACKDOCKERLambdaCDKSTACKINAPIF087084F.POST..receipt
  DOCKERLambdaCDKSTACKINAPIreceiptPOSTApiPermissionTestDOCKERLambdaCDKSTACKDOCKERLambdaCDKSTACKINAPIF087084FPOSTreceipt51A3A08F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DOCKERLambdaCDKSTACKIN240653F3
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
            - /test-invoke-stage/POST/receipt
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Default/receipt/POST/ApiPermission.Test.DOCKERLambdaCDKSTACKDOCKERLambdaCDKSTACKINAPIF087084F.POST..receipt
  DOCKERLambdaCDKSTACKINAPIreceiptPOSTC853DEA1:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: DOCKERLambdaCDKSTACKINAPIreceiptFB018B3A
      RestApiId:
        Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - DOCKERLambdaCDKSTACKIN240653F3
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: DOCKER-Lambda-CDK-STACK/DOCKER-Lambda-CDK-STACK-IN-API/Default/receipt/POST/Resource
Parameters:
  AssetParameterse7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946aS3Bucket122BF8BC:
    Type: String
    Description: S3 bucket for asset "e7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946a"
  AssetParameterse7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946aS3VersionKey750BDFB9:
    Type: String
    Description: S3 key for asset version "e7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946a"
  AssetParameterse7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946aArtifactHash7523DB7E:
    Type: String
    Description: Artifact hash for asset "e7099a62ed1f176b35b98e1ae0c9c07ccd04a17296e90fab4db363508d11946a"
Outputs:
  DOCKERLambdaCDKSTACKINAPIEndpoint7FF8B569:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: DOCKERLambdaCDKSTACKINAPI78B7144F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: DOCKERLambdaCDKSTACKINAPIDeploymentStageprod1BEFA08B
          - /

