Resources:
  SLACKTECHSUPPORTQUEUE8255F2C0:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SLACK_TECH_SUPPORT_QUEUE
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 300
    Metadata:
      aws:cdk:path: BotTemplateCdkStack/SLACK_TECH_SUPPORT_QUEUE/Resource
  SLACKTECHSUPPORTQUEUEPolicy79DEFBFA:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - SQS:*
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::GetAtt:
                - SLACKTECHSUPPORTQUEUE8255F2C0
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: SLACKTECHSUPPORTQUEUE8255F2C0
    Metadata:
      aws:cdk:path: BotTemplateCdkStack/SLACK_TECH_SUPPORT_QUEUE/Policy/Resource
  SLACKBOTLAMBDAROLEF75EE426:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: SLACK_BOT_LAMBDA_ROLE
    Metadata:
      aws:cdk:path: BotTemplateCdkStack/SLACK_BOT_LAMBDA_ROLE/Resource
  SLACKBOTLAMBDAROLEDefaultPolicy1BF652CB:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Effect: Allow
            Resource: arn:aws:sqs:*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: SLACKBOTLAMBDAROLEDefaultPolicy1BF652CB
      Roles:
        - Ref: SLACKBOTLAMBDAROLEF75EE426
    Metadata:
      aws:cdk:path: BotTemplateCdkStack/SLACK_BOT_LAMBDA_ROLE/DefaultPolicy/Resource
  SLACKBOTSQSPUBLISHER6F807C6E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2S3Bucket0F8E24C2
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2S3VersionKey4057CD51
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2S3VersionKey4057CD51
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - SLACKBOTLAMBDAROLEF75EE426
          - Arn
      Runtime: nodejs12.x
      FunctionName: SLACK_BOT_SQS_PUBLISHER
      Timeout: 3
    DependsOn:
      - SLACKBOTLAMBDAROLEDefaultPolicy1BF652CB
      - SLACKBOTLAMBDAROLEF75EE426
    Metadata:
      aws:cdk:path: BotTemplateCdkStack/SLACK_BOT_SQS_PUBLISHER/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/bot-template-cdk/lambdas/slack-bot-sqs-publisher
      aws:asset:property: Code
Parameters:
  AssetParameters28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2S3Bucket0F8E24C2:
    Type: String
    Description: S3 bucket for asset "28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2"
  AssetParameters28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2S3VersionKey4057CD51:
    Type: String
    Description: S3 key for asset version "28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2"
  AssetParameters28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2ArtifactHashEDBFC8F5:
    Type: String
    Description: Artifact hash for asset "28661223d28ed603fda1bdf62d63c3f9f176be4a3e125c5ddb7cdeb81ae8eae2"

