Description: STEP-FUNCTION-CDK-STACK
Resources:
  STEPTESTBUCKET5E9D2B1C:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: step-test-bucket.huge.head.li
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_TEST_BUCKET/Resource
  STEPPUTS3ENTRYLAMBDAROLE88906485:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: STEP_PUT_S3_ENTRY_LAMBDA_ROLE
      RoleName: STEP_PUT_S3_ENTRY_LAMBDA_ROLE
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_PUT_S3_ENTRY_LAMBDA_ROLE/Resource
  STEPPUTS3ENTRYLAMBDAROLEDefaultPolicyD48B8B95:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: arn:aws:s3:::*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: STEPPUTS3ENTRYLAMBDAROLEDefaultPolicyD48B8B95
      Roles:
        - Ref: STEPPUTS3ENTRYLAMBDAROLE88906485
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_PUT_S3_ENTRY_LAMBDA_ROLE/DefaultPolicy/Resource
  STEPPUTS3ENTRYLAMBDAB74EF8C7:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728S3Bucket2C22B4DD
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728S3VersionKeyC31C292B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728S3VersionKeyC31C292B
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - STEPPUTS3ENTRYLAMBDAROLE88906485
          - Arn
      Runtime: nodejs12.x
      Description: STEP_PUT_S3_ENTRY_LAMBDA
      FunctionName: STEP_PUT_S3_ENTRY_LAMBDA
      MemorySize: 256
      Timeout: 15
    DependsOn:
      - STEPPUTS3ENTRYLAMBDAROLEDefaultPolicyD48B8B95
      - STEPPUTS3ENTRYLAMBDAROLE88906485
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_PUT_S3_ENTRY_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/step-function-cdk/lambdas/step-put-s3-entry-lambda
      aws:asset:property: Code
Parameters:
  AssetParameters8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728S3Bucket2C22B4DD:
    Type: String
    Description: S3 bucket for asset "8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728"
  AssetParameters8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728S3VersionKeyC31C292B:
    Type: String
    Description: S3 key for asset version "8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728"
  AssetParameters8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728ArtifactHash8C2A28AF:
    Type: String
    Description: Artifact hash for asset "8de617bec398120d11d7afa85578c43f07a908fa9a818f866535c27f2304c728"

