Resources:
  LAYERPythonCdkSTACKROLENAME30231038:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: LAYER-Python-Cdk-STACK-ROLE_NAME
    Metadata:
      aws:cdk:path: LAYER-Python-Cdk-STACK/LAYER-Python-Cdk-STACK-ROLE_NAME/Resource
  LAYERPythonCdkSTACKROLENAMEDefaultPolicyB8A44098:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: LAYERPythonCdkSTACKROLENAMEDefaultPolicyB8A44098
      Roles:
        - Ref: LAYERPythonCdkSTACKROLENAME30231038
    Metadata:
      aws:cdk:path: LAYER-Python-Cdk-STACK/LAYER-Python-Cdk-STACK-ROLE_NAME/DefaultPolicy/Resource
  LAYERPythonCdkSTACKLAYER67EFF32C:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParameters9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4cS3BucketE97E6271
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4cS3VersionKey9395FDB5
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4cS3VersionKey9395FDB5
      CompatibleRuntimes:
        - python3.8
      Description: LAYER-Python-Cdk-STACK-LAYER
      LayerName: LAYER-Python-Cdk-STACK-LAYER
    Metadata:
      aws:cdk:path: LAYER-Python-Cdk-STACK/LAYER-Python-Cdk-STACK-LAYER/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/layer-python-cdk/Python/Layer
      aws:asset:property: Content
  LAYERPythonCdkSTACKLAMBDA796D7EDC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersd2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980S3BucketDC4F85D6
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersd2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980S3VersionKey648F26EF
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersd2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980S3VersionKey648F26EF
      Role:
        Fn::GetAtt:
          - LAYERPythonCdkSTACKROLENAME30231038
          - Arn
      FunctionName: LAYER-Python-Cdk-STACK-LAMBDA
      Handler: app.lambdaHandler
      Layers:
        - Ref: LAYERPythonCdkSTACKLAYER67EFF32C
      Runtime: python3.8
    DependsOn:
      - LAYERPythonCdkSTACKROLENAMEDefaultPolicyB8A44098
      - LAYERPythonCdkSTACKROLENAME30231038
    Metadata:
      aws:cdk:path: LAYER-Python-Cdk-STACK/LAYER-Python-Cdk-STACK-LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/layer-python-cdk/Python/Lambda
      aws:asset:property: Code
  LAYERPythonCdkSTACKLAMBDATESTA0B39198:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersbe116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efadS3BucketB4D9B672
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbe116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efadS3VersionKey9B66506E
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbe116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efadS3VersionKey9B66506E
      Role:
        Fn::GetAtt:
          - LAYERPythonCdkSTACKROLENAME30231038
          - Arn
      FunctionName: LAYER-Python-Cdk-STACK-LAMBDA_TEST
      Handler: app.lambdaHandler
      Runtime: python3.8
    DependsOn:
      - LAYERPythonCdkSTACKROLENAMEDefaultPolicyB8A44098
      - LAYERPythonCdkSTACKROLENAME30231038
    Metadata:
      aws:cdk:path: LAYER-Python-Cdk-STACK/LAYER-Python-Cdk-STACK-LAMBDA_TEST/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/layer-python-cdk/Python/Lambda-test
      aws:asset:property: Code
Parameters:
  AssetParameters9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4cS3BucketE97E6271:
    Type: String
    Description: S3 bucket for asset "9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4c"
  AssetParameters9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4cS3VersionKey9395FDB5:
    Type: String
    Description: S3 key for asset version "9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4c"
  AssetParameters9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4cArtifactHash4C3EA738:
    Type: String
    Description: Artifact hash for asset "9a2391cb7fa58ab0fc80308df7a656653c191822bd72631bbd424ae4b2616f4c"
  AssetParametersd2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980S3BucketDC4F85D6:
    Type: String
    Description: S3 bucket for asset "d2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980"
  AssetParametersd2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980S3VersionKey648F26EF:
    Type: String
    Description: S3 key for asset version "d2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980"
  AssetParametersd2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980ArtifactHash9A687CAE:
    Type: String
    Description: Artifact hash for asset "d2553a4c1d9428107895967609f205afefadd2f131816c928350864c9d28f980"
  AssetParametersbe116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efadS3BucketB4D9B672:
    Type: String
    Description: S3 bucket for asset "be116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efad"
  AssetParametersbe116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efadS3VersionKey9B66506E:
    Type: String
    Description: S3 key for asset version "be116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efad"
  AssetParametersbe116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efadArtifactHash238CBB4F:
    Type: String
    Description: Artifact hash for asset "be116a238c7f50be9e97d99f38c2e66702357bc7ffdc4dd2f91defd957c1efad"

