Description: STEP-FUNCTION-CDK-STACK
Resources:
  STEPTESTBUCKET5E9D2B1C:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: step-test-bucket.huge.head.li
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_TEST_BUCKET/Resource
  STEPEXAMPLESTEP1LAMBDAROLE1E1B6F41:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: STEP_EXAMPLE_STEP_1_LAMBDA_ROLE
      RoleName: STEP_EXAMPLE_STEP_1_LAMBDA_ROLE
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_EXAMPLE_STEP_1_LAMBDA_ROLE/Resource
  STEPEXAMPLESTEP1LAMBDAROLEDefaultPolicy2ABAC98B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: STEPEXAMPLESTEP1LAMBDAROLEDefaultPolicy2ABAC98B
      Roles:
        - Ref: STEPEXAMPLESTEP1LAMBDAROLE1E1B6F41
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_EXAMPLE_STEP_1_LAMBDA_ROLE/DefaultPolicy/Resource
  STEPEXAMPLESTEP1LAMBDA549BA457:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0S3BucketA4EEE6D9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0S3VersionKey891E27AB
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0S3VersionKey891E27AB
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - STEPEXAMPLESTEP1LAMBDAROLE1E1B6F41
          - Arn
      Runtime: nodejs12.x
      Description: STEP_EXAMPLE_STEP_1_LAMBDA
      FunctionName: STEP_EXAMPLE_STEP_1_LAMBDA
      MemorySize: 256
      Timeout: 15
    DependsOn:
      - STEPEXAMPLESTEP1LAMBDAROLEDefaultPolicy2ABAC98B
      - STEPEXAMPLESTEP1LAMBDAROLE1E1B6F41
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_EXAMPLE_STEP_1_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/step-function-cdk/lambdas/step-example-step-1-lambda
      aws:asset:property: Code
  STEPPUTS3ENTRYLAMBDAROLE88906485:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: STEP_PUT_S3_ENTRY_LAMBDA_ROLE
      RoleName: STEP_PUT_S3_ENTRY_LAMBDA_ROLE
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_PUT_S3_ENTRY_LAMBDA_ROLE/Resource
  STEPPUTS3ENTRYLAMBDAROLEDefaultPolicyD48B8B95:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: arn:aws:s3:::*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: STEPPUTS3ENTRYLAMBDAROLEDefaultPolicyD48B8B95
      Roles:
        - Ref: STEPPUTS3ENTRYLAMBDAROLE88906485
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_PUT_S3_ENTRY_LAMBDA_ROLE/DefaultPolicy/Resource
  STEPPUTS3ENTRYLAMBDAB74EF8C7:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersbe50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4S3Bucket7DCF2D56
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbe50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4S3VersionKeyE7345F09
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbe50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4S3VersionKeyE7345F09
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - STEPPUTS3ENTRYLAMBDAROLE88906485
          - Arn
      Runtime: nodejs12.x
      Description: STEP_PUT_S3_ENTRY_LAMBDA
      FunctionName: STEP_PUT_S3_ENTRY_LAMBDA
      MemorySize: 256
      Timeout: 15
    DependsOn:
      - STEPPUTS3ENTRYLAMBDAROLEDefaultPolicyD48B8B95
      - STEPPUTS3ENTRYLAMBDAROLE88906485
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_PUT_S3_ENTRY_LAMBDA/Resource
      aws:asset:path: /home/song/Sandbox/aws-cdk-examples/step-function-cdk/lambdas/step-put-s3-entry-lambda
      aws:asset:property: Code
  STEPTESTSTATEMACHINERole91B31E87:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_TEST_STATE_MACHINE/Role/Resource
  STEPTESTSTATEMACHINERoleDefaultPolicy06634A72:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - STEPEXAMPLESTEP1LAMBDA549BA457
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - STEPPUTS3ENTRYLAMBDAB74EF8C7
                - Arn
        Version: "2012-10-17"
      PolicyName: STEPTESTSTATEMACHINERoleDefaultPolicy06634A72
      Roles:
        - Ref: STEPTESTSTATEMACHINERole91B31E87
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_TEST_STATE_MACHINE/Role/DefaultPolicy/Resource
  STEPTESTSTATEMACHINE22E68A77:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - STEPTESTSTATEMACHINERole91B31E87
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"STEP_TEST_MACHINE_STEP_1","States":{"STEP_TEST_MACHINE_STEP_1":{"Next":"STEP_TEST_MACHINE_STEP_WAIT","Type":"Task","OutputPath":"$.Payload","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"
            - Fn::GetAtt:
                - STEPEXAMPLESTEP1LAMBDA549BA457
                - Arn
            - '","Payload.$":"$"}},"STEP_TEST_MACHINE_STEP_WAIT":{"Type":"Wait","Seconds":30,"Next":"STEP_TEST_MACHINE_STEP_2"},"STEP_TEST_MACHINE_STEP_2":{"End":true,"Type":"Task","InputPath":"$","OutputPath":"$.Payload","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"
            - Fn::GetAtt:
                - STEPPUTS3ENTRYLAMBDAB74EF8C7
                - Arn
            - '","Payload.$":"$"}}},"TimeoutSeconds":300}'
      StateMachineName: STEP_TEST_STATE_MACHINE
    DependsOn:
      - STEPTESTSTATEMACHINERoleDefaultPolicy06634A72
      - STEPTESTSTATEMACHINERole91B31E87
    Metadata:
      aws:cdk:path: STEP-FUNCTION-CDK-STACK/STEP_TEST_STATE_MACHINE/Resource
Parameters:
  AssetParameters6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0S3BucketA4EEE6D9:
    Type: String
    Description: S3 bucket for asset "6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0"
  AssetParameters6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0S3VersionKey891E27AB:
    Type: String
    Description: S3 key for asset version "6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0"
  AssetParameters6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0ArtifactHashD616C71C:
    Type: String
    Description: Artifact hash for asset "6314d1ddf0a9f39486303b9e947f5baebd772b469ccc73459dc39d01d3d1aeb0"
  AssetParametersbe50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4S3Bucket7DCF2D56:
    Type: String
    Description: S3 bucket for asset "be50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4"
  AssetParametersbe50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4S3VersionKeyE7345F09:
    Type: String
    Description: S3 key for asset version "be50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4"
  AssetParametersbe50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4ArtifactHash65B2EDD0:
    Type: String
    Description: Artifact hash for asset "be50147acaaed8cef299e25099a4a98a278a4b8bd08175b8f352d64786f020a4"

