#!/bin/bash

aws codebuild start-build --project-name CODEBUILD-CDK-STACK-MY-PROJECT  --environment-variables-override name=A,value=A-value,type=PLAINTEXT name=B,value=B,type=PARAMETER_STORE | grep id